# Generated by Django 5.2.3 on 2025-06-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_interviewentry_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewentry',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
